### ISSUE TITLE
Double url encoding for SAMLRequest

### ISSUE THREAD

**Issue by sscarduzio** [node-saml/passport-saml#343]
We are seeing that the generated SSO URLs contain a SAMLRequest query parameter whose value is URL-encoded two times. 

When the user presses the button "login with SAML", they are correctly redirected to the IdP by the library, but looking at at this example URL:

`
https://dag.myIdentityprovider.com:8443/dag/saml2/idp/SSOService.php?spentityid=demo-enterprise&SAMLRequest=nVNdj9owEPwrkd%252FzxSUSWAREQVWRrr2IpH3oCzLxAlYT2%252FU6d%252FDv6wRyQm2PB54i7c6OZ2c20%252Fmpqb1XMCiUzEgcRGQ%252BmyJrak0XrT3KDfxuAa3nYBJp38hIayRVDAVSyRpAaitaLL4%252B01EQUW2UVZWqibdeZWQbQRrv0j1PAeI0nYySSTom3o%252FhQTfhgIgtrCVaJq0rRfHEj2J%252FlJRxRJ9imoyDOE1%252BEi%252B%252FUn8Skgt5uK9jdwEh%252FVKWuZ%252B%252FFCXxFohgrHt4qSS2DZgCzKuo4PvmOSNHazXSMOTQKB%252BkBaONQAgMMK5kfTbOhqBSTWiU2f7ayS2iClnPSLyVawrJbL%252FUOxM7%252FDNNx0ny1HXCzstRKLgOi%252BLlKiTQRz1H7V4X9ix49pcWcomG9oaZm0zuW8GGtclMSajVQTjxbmoa3rANqX9z4%252BtVrmpRnR9J%252FbMyDbMfo%252BMg7iuC%252B%252FseSqFhol5w7ixCl1Fdq7els81CRqxpgYSDtOstAu8v02Vo4fTQZS5Vo5kztAsLTqyyg7G3xMva%252BbaB%252FSM234VVtOqoXTl3nzdleHfYULnFSsMkamXsNZr%252F6Zldeh%252FY8d69%252FXtnfwA%253D
`

We see that the SAMLRequest value:  `nVNdj9owEPwrkd%252FzxSUSWAREQVWRrr2IpH3oCzLxAlYT2%252FU6d%252FDv6wRyQm2PB54i7c6OZ2c20%252Fmpqb1XMCiUzEgcRGQ%252BmyJrak0XrT3KDfxuAa3nYBJp38hIayRVDAVSyRpAaitaLL4%252B01EQUW2UVZWqibdeZWQbQRrv0j1PAeI0nYySSTom3o%252FhQTfhgIgtrCVaJq0rRfHEj2J%252FlJRxRJ9imoyDOE1%252BEi%252B%252FUn8Skgt5uK9jdwEh%252FVKWuZ%252B%252FFCXxFohgrHt4qSS2DZgCzKuo4PvmOSNHazXSMOTQKB%252BkBaONQAgMMK5kfTbOhqBSTWiU2f7ayS2iClnPSLyVawrJbL%252FUOxM7%252FDNNx0ny1HXCzstRKLgOi%252BLlKiTQRz1H7V4X9ix49pcWcomG9oaZm0zuW8GGtclMSajVQTjxbmoa3rANqX9z4%252BtVrmpRnR9J%252FbMyDbMfo%252BMg7iuC%252B%252FseSqFhol5w7ixCl1Fdq7els81CRqxpgYSDtOstAu8v02Vo4fTQZS5Vo5kztAsLTqyyg7G3xMva%252BbaB%252FSM234VVtOqoXTl3nzdleHfYULnFSsMkamXsNZr%252F6Zldeh%252FY8d69%252FXtnfwA%253D` needs to be decoded in 4 stages before it can be translated to XML :

1. URL-decode
2. URL-decode (again!)
3. Base64 decode
4. Deflate 

While from SAML specifications, it should be just three:

1. URL-decode 
2. Base64 decode
3. Deflate 

Please note that it seems some idP like Okta or DUO's DAP don't complain about this error. But OpenAM throws this stack trace:

```
ERROR: SAML2Utils.decodeFromRedirect: base 64 decoded result is null

libSAML2:01/21/2019 02:58:03:981 PM GMT: Thread[http-bio-8080-exec-289,5,main]

ERROR: SAML2Utils.decodeFromRedirect: cannot inflate SAMLRequest:

java.util.zip.DataFormatException: invalid bit length repeat

        at java.util.zip.Inflater.inflateBytes(Native Method)

        at java.util.zip.Inflater.inflate(Inflater.java:259)

        at java.util.zip.Inflater.inflate(Inflater.java:280)

        at com.sun.identity.saml2.common.SAML2Utils.decodeFromRedirect(SAML2Utils.java:1298)

        at com.sun.identity.saml2.profile.IDPSSOFederate.getAuthnRequest(IDPSSOFederate.java:1162)

        at com.sun.identity.saml2.profile.IDPSSOFederate.getAuthnRequest(IDPSSOFederate.java:1204)

        at com.sun.identity.saml2.profile.IDPSSOFederate.doSSOFederate(IDPSSOFederate.java:297)

        at com.sun.identity.saml2.profile.IDPSSOFederate.doSSOFederate(IDPSSOFederate.java:132)

        at org.apache.jsp.saml2.jsp.idpSSOFederate_jsp._jspService(idpSSOFederate_jsp.java:123)

        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)

        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)

        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)

        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)

        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)

        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

        at org.forgerock.openam.validation.ResponseValidationFilter.doFilter(ResponseValidationFilter.java:44)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

        at com.sun.identity.setup.AMSetupFilter.doFilter(AMSetupFilter.java:100)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)

        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)

        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)

        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)

        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)

        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)

        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)

        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)

        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)

        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)

        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)

        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

        at java.lang.Thread.run(Thread.java:724)
```

Please advise!

**Comment by markstos** [comment]
If you believe this is a bug in passport-saml, please provide a test case for the test suite which reproduces the issue.

**Comment by newmanw** [comment]
I am seeing the same thing as well.  In my case I am seeing it in RelayState.  The RelayState seems to be encoded twice, when it comes back the RelayState must be decoded twice.

**Comment by cjbarth** [comment]
@newmanw , do you have a tests case for this? We'd certainly like to have this fixed, but we don't have a reliable reproduction to work off of.

**Comment by newmanw** [comment]
@cjbarth good news, I dug a bit more and it was the saml server I was hitting that was re encoding an already encoded value.  Please disregard my comment.
