### ISSUE TITLE
Error: SAMLResponse is not valid base64-encoded XML

### ISSUE THREAD

**Issue by deeptiranjandrb** [node-saml/passport-saml#806]
### Discussed in https://github.com/node-saml/passport-saml/discussions/805

<div type='discussions-op-text'>

<sup>Originally posted by **deeptiranjandrb** November  8, 2022</sup>
I am getting below error in my project: 
`Error: SAMLResponse is not valid base64-encoded XML
    at SAML.validatePostResponseAsync (/Users/dbali00/Documents/pure_repos/customer-management-ui/node_modules/passport-saml/lib/node-saml/saml.js:562:23)
    at MultiSamlStrategy.authenticate (/Users/dbali00/Documents/pure_repos/customer-management-ui/node_modules/passport-saml/lib/passport-saml/strategy.js:80:18)
    at /Users/dbali00/Documents/pure_repos/customer-management-ui/node_modules/passport-saml/lib/passport-saml/multiSamlStrategy.js:28:32
    at findProvider (/Users/dbali00/Documents/pure_repos/customer-management-ui/routes/api-config/passport.js:31:14)
    at Object.getSamlOptions (/Users/dbali00/Documents/pure_repos/customer-management-ui/routes/api-config/passport.js:37:9)
    at MultiSamlStrategy.authenticate (/Users/dbali00/Documents/pure_repos/customer-management-ui/node_modules/passport-saml/lib/passport-saml/multiSamlStrategy.js:21:23)
    at attempt (/Users/dbali00/Documents/pure_repos/customer-management-ui/node_modules/passport/lib/middleware/authenticate.js:369:16)
    at authenticate (/Users/dbali00/Documents/pure_repos/customer-management-ui/node_modules/passport/lib/middleware/authenticate.js:370:7)
    at Layer.handle [as handle_request] (/Users/dbali00/Documents/pure_repos/customer-management-ui/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/dbali00/Documents/pure_repos/customer-management-ui/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/dbali00/Documents/pure_repos/customer-management-ui/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/dbali00/Documents/pure_repos/customer-management-ui/node_modules/express/lib/router/layer.js:95:5)
    at /Users/dbali00/Documents/pure_repos/customer-management-ui/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/dbali00/Documents/pure_repos/customer-management-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/dbali00/Documents/pure_repos/customer-management-ui/node_modules/express/lib/router/index.js:275:10)
    at /Users/dbali00/Documents/pure_repos/customer-management-ui/server-csr-proxy.js:109:5`
    
    Previously the same project was running after building. But it has stopped working. There are no code/package updates in the project.
   I am using version 3.2.0 and tried upgrading to 3.2.4 but still I am receiving the same error. Can somebody please help me with the issue?</div>

**Comment by cjbarth** [comment]
In addition to the always helpful comments by @srd90 , I would also suggest that you use https://www.samltool.com/ to help you test the validity of your XML.

Also, since there is nothing in the discussion you linked to, or in this open issue, about your previously working setup, nor any information about what debugging you've tried, I'm going to close this. If you post with more information, we'll reopen it.
