### ISSUE TITLE
Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag 

### ISSUE THREAD

**Issue by da201501245** [node-saml/passport-saml#808]
Receiving error on encrypted SAML Response.

Error: error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag
    at Object.privateDecrypt (node:internal/crypto/cipher:79:12)
    at decryptKeyInfoWithScheme (/home/myloft/app/node_modules/xml-encryption/lib/xmlenc.js:258:26)
    at decryptKeyInfo (/home/myloft/app/node_modules/xml-encryption/lib/xmlenc.js:246:14)
    at Object.decrypt (/home/myloft/app/node_modules/xml-encryption/lib/xmlenc.js:187:24)
    at node:internal/util:361:7
    at new Promise (<anonymous>)
    at Object.decrypt (node:internal/util:347:12)
    at decryptXml (/home/myloft/app/node_modules/passport-saml/lib/node-saml/xml.js:39:93)
    at SAML.validatePostResponseAsync (/home/myloft/app/node_modules/passport-saml/lib/node-saml/saml.js:591:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

after upgrading node version from `12.20.0` to `16.13.2` and passport-saml to `3.2.4`

I have decryptionPvk is the same as the previous version with the format start line and end line `-----BEGIN RSA PRIVATE KEY-----` and `-----END RSA PRIVATE KEY-----`

earlier this was working fine after upgrading to the latest version it stopped working.

**To Reproduce**
- pass encrypted SAML Response in passport.authenticate() 

**Expected behaviour**
- it should decrypt SAML Response have working on earlier version.

**Environment**

- Node.js version:
-  16.13.2
- `passport-saml` version:
-  3.2.4

**Comment by cjbarth** [comment]
@srd90, that is some good detective work, thanks. I'll close this pending more information from the end user.
